[build]
# python 3.11로 환경 설정
language = "python"

[start]
cmd = "gunicorn app:app"  # Flask 진입점이 app.py에서 app = Flask(__name__)

[packages]
apt = [
  "libgl1",           # ✅ libGL.so.1 오류 해결
  "libglib2.0-0",     # mediapipe/GTK 관련
  "libsm6",           # OpenCV 시각화 관련
  "libxext6",
  "libxrender-dev"
]
